get_tasks_report mod
sysblok/sysblokbot pull request #217
Opened 2021-10-30 16:46 UTC by LenaMenh

get_tasks_report shows trello boards instead of asking url

2021-11-06 22:33 UTC, paulin-mipt requested changes

2021-11-06 22:33 UTC, paulin-mipt commented on src/tg/handlers/user_message_handler.py
> +            assert 0 <= list_idx < len(board_list)
I think the user facing message could be more explicit here. If user_input is not int (what if int() fails?) or int is not in range we could say smth like "expected a single int in range [1, {len(board_list))], try again". Otherwise "something went wrong". Because we can really have actionable or non-actionable errors here

2021-11-06 22:33 UTC, paulin-mipt commented on src/tg/handlers/user_message_handler.py
> +    elif next_action == PlainTextUserAction.GET_TASKS_REPORT__ENTER_BOARD_NUMBER:
Should we eliminate GET_TASKS_REPORT__ENTER_BOARD_URL action altogether as unused?

2021-11-06 22:33 UTC, paulin-mipt commented on src/tg/handlers/user_message_handler.py
> +            assert 0 <= list_idx < len(board_list)
I see the same thing happening below for the lists. I even feel that I was the one who wrote it. Well, this means I'm improving :) Feel free to make it right

2021-11-06 22:33 UTC, paulin-mipt commented on src/tg/handlers/get_tasks_report_handler.py
> +    tg_context.chat_data[consts.GetTasksReportData.LISTS] = [lst.to_dict() for lst in boards_list]
Should it be a new constant, for boards? It'd work with reusing the same value as well, but may be little confusing

2021-11-06 22:33 UTC, paulin-mipt commented on src/tg/handlers/user_message_handler.py
> +            #dublicate request - пока я не поняла, как сохранять контекст
No longer the case, I think

2021-11-09 09:12 UTC, LenaMenh commented on src/trello/trello_client.py
> +        lists = [
I'm for readability. Also there is a logger output with this variable. Let it be a separate value

2021-11-09 09:13 UTC, LenaMenh commented on src/tg/handlers/get_tasks_report_handler.py
> +    # tg_context.chat_data[consts.LAST_ACTIONABLE_COMMAND] = TASK_NAME
ok

2021-11-09 09:15 UTC, LenaMenh commented on src/tg/handlers/user_message_handler.py
> +    elif next_action == PlainTextUserAction.GET_TASKS_REPORT__ENTER_BOARD_NUMBER:
I had left if for some backward compatibility. If the new command flows good - then we can remove old constants and old processing code.

2021-11-09 09:17 UTC, LenaMenh commented on src/tg/handlers/get_tasks_report_handler.py
> +    tg_context.chat_data[consts.GetTasksReportData.LISTS] = [lst.to_dict() for lst in boards_list]
As I understood, .LISTS here are not  only "lists of tasks on board" but also a 'list of parameters we pass through'. I think  it should be only one variable.

2021-11-09 09:18 UTC, LenaMenh commented on src/tg/handlers/user_message_handler.py
> +            #dublicate request - пока я не поняла, как сохранять контекст
ok

2021-11-09 09:38 UTC, LenaMenh commented on src/tg/handlers/user_message_handler.py
> +            assert 0 <= list_idx < len(board_list)
changed a message but didn't updated the error handling

2021-11-10 20:48 UTC, paulin-mipt approved these changes

2021-11-10 20:48 UTC, merged