https://trello.com/c/YNnHScUp
sysblok/sysblokbot pull request #270
Opened 2022-11-06 21:21 UTC by gisly

https://trello.com/c/YNnHScUp

Loading the job config from the Google drive

2022-11-06 23:19 UTC, alexeyqu commented on src/tg/handlers/access_config_handler.py
> +        jobs_config_json = AppContext().drive_client.download_file(jobs_config_file_key)
we return `bytes` but parse as json, hmm

2022-11-06 23:20 UTC, alexeyqu commented on src/drive/drive_client.py
> +                status, done = downloader.next_chunk()
ouch, looks complicated.. Is `MediaIoBaseDownload` the best class to use?

2022-11-06 23:21 UTC, alexeyqu requested changes
Can you add some words to PR title (not only the Trello URL)?
Have a look at some questions on the Drive API/client usage.

2022-11-07 07:38 UTC, gisly commented on src/tg/handlers/access_config_handler.py
> +        jobs_config_json = AppContext().drive_client.download_file(jobs_config_file_key)
https://docs.python.org/3/library/json.html#json.loads loads seems to work well with bytes but I can parse right here to make it more readable

2022-11-15 03:56 UTC, alexeyqu approved these changes

2022-11-15 22:00 UTC, merged